### ISSUE TITLE
BIP32 : Use native Segwit BIP-173 key ?

### ISSUE THREAD

**Issue by julien-boudry** [iancoleman/bip39#121]
Hi,

Waiting for a possible new BIP dedicated standard. BIP32 tab could add an option for using the P2WKH address following BIP-173?

**Comment by iancoleman** [comment]
Good idea, thanks for submitting it.

I'd say probably BIP173 would be a new tab, which would have content very similar to bip32 tab. This is similar in scope to https://github.com/iancoleman/bip39/issues/119 which removes the segwit option from the bip32 tab into a separate bip141 tab.

A link to bip173 for my future reference:

https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki
Base32 address format for native v0-16 witness outputs

**Comment by Raulo** [comment]
The standardization is getting urgent because wallets start to implement BIP-173 and may become not inter-operable.

What about a simple solution, following BIP43, to use purpose=173? So 
m/173'/0'/0' is the root for BIP173 addresses on mainnet. With version bytes proposed here:
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-September/014907.html

**Comment by iancoleman** [comment]
```
0x049d7878 yprv        (P2WPKH or P2WSH) nested in P2SH
0x049d7cb2 ypub        (P2WPKH or P2WSH) nested in P2SH
```

yprv / ypub has been implemented, see https://github.com/iancoleman/bip39/commit/93c3ef47579733040dbc6eec865b528d1ca49911

```
0x04b2430c zprv        P2WPKH or P2WSH
0x04b24746 zpub        P2WPKH or P2WSH
```

zprv / zpub still needs to be implemented (along with P2WPKH), which will be done as this issue is developed.

I'm not sure how urgent this is. Some links to indicate the uptake of this format would be appreciated if they're available. My workload is very high just now so if this is something people are actually using I'll bump it up the priority list, but if nobody is currently using it I'd rather leave it alone in the short term.

**Comment by iancoleman** [comment]
Regarding bip173 (bech32) this requires upgrading bitcoinjs-lib from the 3.1.1 (which is currently in use by this tool but [does not support bech32](https://github.com/bitcoinjs/bitcoinjs-lib/blob/v3.1.1/src/networks.js)) to at least 3.2.0 (which [does support bech32](https://github.com/bitcoinjs/bitcoinjs-lib/blob/v3.2.0/src/networks.js)).

**Comment by iancoleman** [comment]
See

* https://github.com/iancoleman/bip39/commit/9f59e99bec5cc5faa63c0296f064a09b0745291f - Update bitcoinjs from v3.1.1 to v3.3.0
* https://github.com/iancoleman/bip39/commit/0fd67b5915a08168d31caaa581f55cf86591be73 - Remove segwit from bip32 tab
* https://github.com/iancoleman/bip39/commit/c49e881294343b762109bb8104e7c1b45898c894 - Add BIP141 tab for full segwit compatibility

These changes will be included in the next release.

**Comment by Raulo** [comment]
@iancoleman 

Thank you for the update. It will definitely help with BIP173 adoption to have a reference implementation and a common derivation scheme for wallet interchangeability.  

I have a few comments, though.

1. I think it would be better if the tab was labeled BIP173 and not BIP141 because essentially, it implements BIP173, BIP141 is more general and does not describe bech32.
2. I think it does not have sense to have a P2WPKH nested in P2SH as a option together with bech32 one. P2WPKH nested in P2SH is defined in BIP49 and there is no need to duplicated it. 
3. The derived keys are not compatible with Electrum. I tried "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about" seed, it generates zprvAZR2dpDbwmU74mPJboas8xBwaFtNCCGCp3Q2aBc1LgUxLfcYetS24FtpfmfTfoQJsRiVX3Dn4gXNLKRv1QpFHi2hkrfbcULuQQkNgni2623 BIP32 extended P2WPKH private key. The key imported to Electrum gives bc1q2utxmwa2h7u4e90ex2eqdfyy4g5v66pny4vy93 as the first address, while your tool generates bc1qrh98qvlnec9k9au5auntfj3y2tmmw9w0353lqd. I'm not very familiar with your tool so I cannot track the issue myself but I'm willing to help.

**Comment by iancoleman** [comment]
Thanks for the considerations.

I'll explain the reasoning I've used to make each decision. I'm open to being wrong on this so if you think the reasoning isn't sound please let me know the alternative reasoning.

1. The tab implements segwit ([bip141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#Examples)), of which bech32 ([bip173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki)) is one of several formats. Bech32 is a particular address format, "a standard for native segregated witness output addresses". But segwit also works with other address formats, such as p2wpkh-in-p2sh. So the tab, being a segwit tab and not a bech32 tab, should be labelled bip141. I think the generality of bip141 makes it a stronger contender for the title, since it's more useful to more people than the restricted case of only bech32 addresses.

2. P2WPKH nested in P2SH is defined in bip141, not bip49. bip49 simply *uses* that format, does not *define* it. So I think p2wpkh-in-p2sh definitely does have a place on a tab other than bip49, and that place should be the bip141 tab. This is also another reason against point 1.

3. The root key (ie not derived extended key) is compatible with electrum (when this tool has derivation path set to m/0). At first I was confused but then realized probably electrum uses m/0 for receive addresses and m/1 for change addresses, like bip44 and bip49. It may be helpful to add some details about specific clients (similar to the bip32 tab). So to correctly use this tool with electrum

    1. generate mnemonic
    1. select bip141 tab with p2wpkh
    1. copy the root zprv key, not the extended zprv key
    1. import the root zprv key into electrum
    1. observe the electrum receive address matches the table in this tool

Hopefully this clarifies the decisions. I'm open to ideas if the reasoning needs improvement.

**Comment by Raulo** [comment]
I'm sorry it took me so much time to comment again.

1. BIP141 and BIP173 is a matter of taste and I would not strongly object to BIP141, though I still think that BIP173 is better choice since BIP141 is more general and the address format is not complete without BIP173. At the time BIP141 was created, it was possible we were going to get BIP142 that was later dropped. 

2. I'm really confused here. Why do we need a separate incompatible P2WPKH nested in P2SH implementation when BIP49 is widely used? Trezor, Ledger and Electrum recognize BIP49 and generate compatible wallets. Your tool generates the same root key but since the default derivation path is m/0, it generates incompatible addresses. What about removing this tab (to avoid confusion) or at least put m/49'/0'/0'/0 derivation path as default to get the same wallet as in BIP49 and be compatible with BIP43 specification that requires purpose? 

3. OK it works following your instructions.

4. I think, however, that it would be good if for the pure P2WPKH, the  BIP32 Derivation Path was something other than simply m/0 (again to follow BIP43). So far all the derivation paths had contained encoded purpose. You had to just write down the seed and m/44'/0' or m/49'/0' (for bitcoin). Now you have to remember separately seed, m/0 and also that it is used for bech32. What about m/173'/0' path, or if you still think BIP141 is a better labeling choice, at least  m/141'/0'?

**Comment by iancoleman** [comment]
> Why do we need a separate incompatible P2WPKH nested in P2SH implementation when BIP49 is widely used?

This is the same as asking why do we need bip32 tab when we have bip44 tab.

bip49 is 'formal' p2wpkh-p2sh, bip84 is 'formal' p2wpkh, bip141 is 'general advanced-mode' segwit. Bip141 is not meant to be restricted by purpose etc, just like how bip32 tab has no restrictions on derivation.

I think bip141 tab could be changed to select bip173 bech32 by default instead of p2sh, but other than that I think the feature is correct and complete.
