### ISSUE TITLE
Please add support for ZCash

### ISSUE THREAD

**Issue by avibrazil** [iancoleman/bip39#136]
ZCash is m/44'/133'/...

Using these parameters on BIP32 tab doesn't give correct addresses.

Please. Thank you.

**Comment by iancoleman** [comment]
Best to ask on a zcash forum for a technical person to contribute this change. I am unable to add new networks myself because I don't know the values for the network parameters.

To get an idea of the network parameters required for zcash to work, have a look at the changes for, say, nubits - https://github.com/iancoleman/bip39/commit/8dd28f2cff4e1f673f4aa7adc93a7254de72a297

If someone can provide a pull request to add zcash that would be fantastic.

**Comment by alkley** [comment]
I tried adding zcash a while ago, but there were problems with their network parameters and the latest versions of bitcoinjs. See #94

**Comment by iancoleman** [comment]
Ah of course, I remember the issue now. I think best to keep this all in one place. I'll close this and add 'zcash' to the title of #94 so it's clearer in the future. Thanks @alkley.
