### ISSUE TITLE
enhancement - passing parameters into webpage

### ISSUE THREAD

**Issue by johndpope** [iancoleman/bip39#162]
<img width="268" alt="screen shot 2018-02-06 at 2 57 12 pm" src="https://user-images.githubusercontent.com/289994/35881184-0647679e-0b4e-11e8-903a-d18d76215458.png">

building an iphone test wallet - and would like to open webpage and pass in the values to inspect the entropy details to verify generated key - 
https://github.com/kishikawakatsumi/BitcoinKit

eg 
https://iancoleman.io/bip39/ entropy = fbb40c0fca2a99fb9444a1f84938c1477861969d

then show 

![screen shot 2018-02-06 at 2 59 15 pm](https://user-images.githubusercontent.com/289994/35881291-5e8f8184-0b4e-11e8-8351-df286119d796.png)

**Comment by iancoleman** [comment]
Thanks for this, I see what you mean.

By way of example, if you click on a different language for the mnemonic you'll see that the url hash changes to indicate the language. This also works the other way, ie allows the language to be specified; eg if you load https://iancoleman.io/bip39/#japanese and then press generate, it'll generate in Japanese rather than English.

So there's definitely scope for including prepopulated fields to the page via the url hash. I'll look into doing this. Your suggestion gives me a good idea of the possible use cases to design for.

**Comment by johndpope** [comment]
I guess a Json end point would probably be most flexible.
