### ISSUE TITLE
Korean is not supported.

### ISSUE THREAD

**Issue by munggo** [iancoleman/bip39#170]
Korean is not supported.
Please support Korean.

**Comment by iancoleman** [comment]
Thanks for this.

Wordlist is here: https://github.com/bitcoin/bips/blob/master/bip-0039/korean.txt

I'll add this to the next release.

**Comment by munggo** [comment]
Thank you.
Please be sure to add it in the next release.
When do you expect the next release?

**Comment by iancoleman** [comment]
Should be a new release early to middle of next week.

**Comment by munggo** [comment]
thank you.
Please add features.

**Comment by iancoleman** [comment]
This has been released in v0.3.4

See https://github.com/iancoleman/bip39/commit/139becaf2cc22c99e2813098c1411164c9baef26 - Add Korean language

Currently the mnemonic is displayed with ideographic spaces, however it should apparently use ascii spaces (see https://github.com/bitcoin/bips/pull/570#issuecomment-372166421). Since the mnemonic is nfkd normalized the difference in spaces don't affect the resulting keys, but it should be changed to use ascii space if that's what's normal for Korean language.

**Comment by munggo** [comment]
Thank you.
But not yet. It is not that simple.
If you click the "한국어" button, the sample word will be input and it will work normally.
Copy and paste the words in the Textarea Box.
"not in wordlist, did you mean able?" Is displayed.
This seems to be an ASCII and Unicode issue.

**Comment by munggo** [comment]
I use Safari web browser mainly.
It works fine in Chrome.
Thank you. Have a nice day.

**Comment by iancoleman** [comment]
Thanks for reporting the issue with Safari. I don't have immediate access to that browser but when I do later I will try it out and see if I can resolve it since Safari is a very common browser.
