### ISSUE TITLE
BTG coin number 0, not 156

### ISSUE THREAD

**Issue by kys86468** [iancoleman/bip39#189]
Hello.
According to https://github.com/satoshilabs/slips/blob/master/slip-0044.md coin number for BTG is 156, but here is 0. Why is it?

**Comment by iancoleman** [comment]
You're right it looks like it should be 156

The commit for btg to this tool by @rsnel here: https://github.com/iancoleman/bip39/commit/3960807353a4dfd44620d418ac7b2e393dccafd6

The slip0044 reservation was about one month prior here:
https://github.com/satoshilabs/slips/commit/9ee7b4b020ae1fc76855f7cfd0d691619c8f6c3a

@rsnel any reason why this was committed with 0 instead of 156? Can it be changed to 156 safely?

**Comment by kys86468** [comment]
And here number is 156 - https://github.com/Coinomi/bip39/commit/2d0a0a613d63d5df72fa9d9309cb250c289bb962

**Comment by rsnel** [comment]
I used value 0 to access my split coins. It can safely be changed to 156.
