### ISSUE TITLE
Cleanup info part

### ISSUE THREAD

**Issue by skironDotNet** [iancoleman/bip39#260]
Can this section be removed?
1. the site does not exits
2. it makes no sense even if it would

![ian-brain](https://user-images.githubusercontent.com/2981715/46485077-96a76080-c7c0-11e8-9700-94503f2d33e4.png)

**Comment by hatgit** [comment]
In case it's not removed (for any sake of pointing out the limitation of using such brain wallets) perhaps consider swapping with https://brainwallet.io/

**Comment by skironDotNet** [comment]
Good to know this tool exists, I see why it's better than just using phrase it has more factors, I think that's the key. 
Going back to "remove this" what makes no complete sense to me is "Use private keys at..."
Why would anybody want to use private keys elsewhere, I mean which private keys? the generated addresses by Bip39 tool, or to use the mnemonic seed in there? I don't think one goes with another.
You either generate bip39 words and use bip39 too create new addresses and accounts, or you use a brain wallet to generate single address from your "own text" you could I guess use "phrase"1 "phrase"2 at brainwallet to generate difftent addresses from same base "phrase".

I have combined solution for "custom text" and multi address, multi account. Menmonic then serves as "checksum" need to remeber just 1st and last word to verify I entered my phrase correctly ie no mistype
https://greenhex.net/bip39-personal-standalone.html

Going back again to "Private Keys" section it makes no sense in my opinion to keep it, but I'm awaiting reasonable justification to keep it.

**Comment by iancoleman** [comment]
The reason this phrase and link is there is for further details about the private/public key part of the wallet for any individual keypair/address which isn't available directly in the table (eg ASN.1 Key, HASH160).

This tool used to not include public key info or qr codes so the link to brainwallet was useful for filling those missing features, but now these features are here the link is less relevant. I'll consider removing the link, but would prefer to replace it with something else rather than remove it altogether to provide more detail for keypairs than is available in just the table.
