### ISSUE TITLE
Update Online Tool

### ISSUE THREAD

**Issue by kaypon** [iancoleman/bip39#270]
More of a question than an issue. Just wanted to know when does the [online tool](https://iancoleman.io/bip39/) get updated to show new coins added?

I made a [pull request](https://github.com/iancoleman/bip39/pull/267) that was merged 14 October 2018. However, the online tool still does not show our coin in the coin drop down.

Thanks for your time.

Kevin

**Comment by iancoleman** [comment]
Good question. Part of this is because there have only been new networks added since the last version, and I prefer to add some 'real' features for each release. The other reason is I'm lazy and haven't updated when really I should have. Also some tests were failing but they're passing now. I'll try to get to doing a new release today.
