### ISSUE TITLE
Compatibility with Electrum (2.7.11) and in general more wallets.

### ISSUE THREAD

**Issue by neocogent** [iancoleman/bip39#37]
I've just been doing a few tests in viability of using this tool to generate BIP39 seeds for Electrum. It does work to some extent but there is some strangeness about how root keys, xprv and xpubs interact and I'm looking  for some clarity on how/why there seems to be differences in how these are created and why they don't match for matching seeds.

As an example, I can use this tool to generate a random seed (12 words): spin hobby shoot crunch riot coil creek arctic usage produce dance blood

And the root key is: xprv9s21ZrQH143K45vQYApHCpF2TSVhyeQ9h5EoFRf3nY3AFj9KECzDXWxTAqDTryiGF3n44FSnmzr3pnChT1QTYZcvNwN3HY3rwMKkxJXoGns

BIP32 (BIP44 derivation path) xprv is: 
xprvA1aCxyentjgsZXNhyqSKu6BytDEohr2NidfmCCV38vQaGcoJftBM4PLPcr6g6RhSMAshUE8npU4nYMgC8BVtR6BGr1fLnjZPsvuuHMPDqoB

BIP32 (BIP44 derivation path) xpub is: 
xpub6EZZNVBgj7FAn1TB5ryLGE8iSF5J7JkE5rbMzatehFwZ9R8TDRVbcBesU7LomwFNYwUzVxJCcJRh2uwfkHLVCQFJ8zgs4yZ3bak9yXHBTaD

Restoring this seed to Electrum (as BIP39) creates the same address list: 1KtVmkercr9AiNcN9QTozKbL42L6tnrv3i ...
(which is great, as this makes this a useful and compatible tool, initially).

But the actual xprv stored in the Electrum wallet is different from above:
xprv9yeoQ31aaJA1k9WSwqyrT1ekYdViDsgRzMQquePrbTdiSVFRzRF9ECEvJNiXqWUEfSes7hbKPBgRPpthYuG5u7UBpZwz7XXzceaTpFPP5Le
(and when this is pasted into this tool as root key it gives a differing address list - so root key here is not the same as xprv in Electrum).

And when the BIP32 xprv above, from this tool, is used to restore a wallet you get a different address list.

But what I find most confusing is that the seed word list I started with above results in an xpub that is not usable in Electrum. From this tool above, 

xpub6EZZNVBgj7FAn1TB5ryLGE8iSF5J7JkE5rbMzatehFwZ9R8TDRVbcBesU7LomwFNYwUzVxJCcJRh2uwfkHLVCQFJ8zgs4yZ3bak9yXHBTaD

compared to the one Electrum generates for same seed words,

xpub6Ce9oYYUQfiJxdav3sWrp9bV6fLCdLQHMaLSi2oU9oAhKHaaXxZPmzZQ9fqwNq6a3rFqRniJz7z94uhVPidAs2hiPAfAD4WDJKR7RZJw6oM

Hence, while you could use this tool to generate a seed word list and create an Electrum wallet with same addresses, the matching xpub will not generate a same watch-only wallet - even though on this tool the xpub given supposedly matches the same address list. Weird? Or not? Either xpubs are not deterministic for seed words, or there is a bug in the xpub calculation (here or in Electrum) or some differing derivation method maybe? Strangely, the address list does match!

**I would like to work out what's going on here so that some clear process exists for using this tool in a useful and reliable way with Electrum in general (and maybe other wallets).** Any explanation possible of what reliably works would be helpful.

I question the validity of the xpub shown by this tool when the differing xpub in Electrum does create a watch-only wallet with same address list as this tool. And the xpub from this tool when likewise plugged into Electrum (same restore, standard, by public key, xpub pasted) creates a different address list than here.

I know it's not your fault but the whole BIP32/BIP39/BIP44 world is currently a holy f** mess as compatibility between nearly all existing wallets is very spotty at best - according to this online reference matrix:

https://onedrive.live.com/view.aspx?resid=584F122BA17116EE!313&app=Excel

**Comment by iancoleman** [comment]
Thanks for this detailed issue report.

I'm backlogged until next week but let me answer what I can now.

> Restoring this seed to Electrum (as BIP39) creates the same address list, But the actual xprv stored in the Electrum wallet is different from above.

The xprv stored in electrum is derived using the path `m/44'/0'/0'`

This is *one level up* from the BIP44 tab path of `m/44'/0'/0'/0`

The reason for this is electrum needs to be able to generate `m/44'/0'/0'/0/X` (ie the external addresses), *as well as* `m/44'/0'/0'/1/X` (ie change addresses). So it stores the level above what you might expect from the BIP44 tab.

Electrum (and all BIP44 wallets) should probably store `m/44'/0'` so they can also scan for multiple accounts, but I guess electrum only uses a single account.

Enter the the electrum xprv key into the tool and use BIP32 tab with derivation path `m/0` to see the list of addresses electrum generates (`m/1` for the change addresses used internally by electrum).

> when the BIP32 xprv above, from this tool, is used to restore a wallet [in electrum] you get a different address list.

Use the mnemonic to restore. Or if using an xprv, use the xprv from the BIP32 tab with derivation path `m/44'/0'/0'`

I need to get the latest electrum to test this, but restoration should always be done with the mnemonic rather than the xprv.

> the seed word list I started with above results in an xpub that is not usable in Electrum.

Use the BIP32 tab and the derivation path `m/44'/0'/0'`

This will give the same xpub as electrum, but not the same addresses for the reason stated above.

On a related tangent, if you enter your electrum xpub into blockchain.info search, it will find all addresses (external and change).

> the matching xpub will not generate a same watch-only wallet

It will when using the correct derivation path for the xpub which is `m/44'/0'/0'`

I will add a section on the BIP32 tab for electrum, which will be identical to the Mycelium section since they work the same way.

The issue comes down to how wallets import / restore, and as you point out there are differences.

In my opinion, wallets should import from the path `m/44'/0'` and should discover both accounts and addresses. But the current expectation seems to be for users to keep track of accounts and the wallet to only gap the addresses. (Actually my real opinion is import should only happen using mnemonics, never xprv or xpub).

See [Account Discovery](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#account-discovery) and [Address Gap Limit](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#address-gap-limit) for more info.

Perhaps this issue illustrates why this tool is a *tool* and not a *wallet*... wallets do a lot of automatic discovery that is somewhat beyond the scope of this tool (at least for now).

Hope this is clear, if not please highlight the specific concerns and I can try to explain it better.

Points of action from this:

* Add electrum to BIP32 tab explanations
* Consider how the BIP44 tab may be clearer for end users wrt account and address discovery.

**Comment by neocogent** [comment]
Thank you for your explanation. I didn't see your response when I had googled about this and found the closed earlier issue #7 which had the derivation path explanation as well. I tested this out in the BIP32 tab and shortened path. It worked as you explained and matched Electrum xpub. So this tool works correctly and I'm happy about that. That is, knowing that the xpub with that path matches Electrum gives me confidence this tool behaves as it should.

The only thing I'd maybe suggest is that on your BIP44 tab perhaps have the External/Internal entry be optional via a blank entry or check box option. So that if a user wants to see an xpub for the whole account and not sub level for ext/int then they could either leave it blank or maybe better, choose to disable it (hides address list?). I think users trying out your tool could then easily see that the upper level account xpub does work for Electrum (and perhaps other wallets) - rather than have to know about the correct way to enter a path in the BIP32 tab. 

I'm happy that there is a reasonable explanation for what I took to be perhaps broken behavior. Your tool is **excellent and very useful** as an offline way of working with seeds, xprv, xpub values. Maybe it just needs a bit more info about how wallets are using these so that users aren't confused about using the tool and getting matching results. 

I'm not currently depending on the tool for actual funds and simply wanted to verify it's use as a backup for future scenarios where Electrum or my hardware wallet aren't available. To this end for a self contained tool that one can store away eg. on an offline boot usb stick it's most useful with extra help info so that users don't have to remember details like this.

I wonder if rather than adding Electrum info to the BIP32 tab it may be better to add a tab for Electrum or common wallets (Mycelium) that use the correct path with some details. That way it's very easy for a user to choose the correct tab and see right away the matching xpub values. Maybe it has a toggle button for int/ext path or lists both address chains.

Anyway, all is good. Thank you for your excellent tool and explanation. I look forward to an update, whichever way you decide to go, that removes confusion.

**Comment by iancoleman** [comment]
This change is in https://github.com/iancoleman/bip39/commit/c554e6ff5c2c543997841c0fb0a506262843e8df - BIP44 Account xprv and xpub keys are shown which are used for import / export in most BIP44 wallets

This change is live at https://iancoleman.github.io/bip39/ and can be seen in the BIP44 tab.

I think this UX is clear, but would appreciate confirmation before closing the issue.

> on your BIP44 tab perhaps have the External/Internal entry be optional via a blank entry or check box option. So that if a user wants to see an xpub for the whole account and not sub level for ext/int then they could either leave it blank or maybe better, choose to disable it (hides address list?).

I see what you're getting at here but I think hiding the address list is not possible, because that list is the primary 'end purpose' of the tool. I feel that hiding that list under any circumstances would be quite confusing. (I'm just making a note of this design choice for posterity. Thanks for bringing it up.)

**Comment by neocogent** [comment]
I had a look and I think that's very clear. It allows people to decide which xprv/xpub they want and how they're different, and should prevent trying to use the wrong ones.

I noticed a minor typo on the line above account keys: The account extende**n**d keys can be used...

I'm fine with closing this, as you like.

**Comment by iancoleman** [comment]
Good catch on the typo

https://github.com/iancoleman/bip39/commit/f3bfd2a5e569db16351821db6c0de5bfb2cf00de - Typo Extendend > Extended
