### ISSUE TITLE
Mnemonic length affects the seed being generated

### ISSUE THREAD

**Issue by a20eac1d** [iancoleman/bip39#404]
Thank you for your work on this project.

I am trying to generate a 24 word mnemonic with the latest version.

- Use "bc8249f88ac9880a2c54db0e851d4b6e4ab5465e3af68d4dc132231640613e76" as hex-based 256 bit entropy
- Set "Mnemonic length" to "use raw entropy (3 words per 32 bits)" (256 bit / 32 = 8 * 3 = 24 words)
- Results in the 24 word mnemonic of: "route banner lawsuit better obtain agree rally opinion attend cigar fan symptom prize permit jump gain minute host erode economy goat correct what slot"

- Use the same entropy as before
- Set "Mnemonic length" to "24 words"
- Results in the 24 word mnemonic of: "color village afford alien scale actual arctic shaft bulk sustain diary wrestle rally afford abuse exchange click valley hub slam hundred skate diesel prefer"

In both cases, the raw binary entropy stays the same but the binary checksum changes and with that the word indexes.

Why is that?

Is this a known issue?

**Comment by iancoleman** [comment]
Fixed word length hashes the entropy, whereas raw entropy does not. This is so that unusual entropy lengths can be encoded, eg it becomes possible to encode, say, 243 bits of entropy into a mnemonic (which would appear to contain 256 bits of entropy but in reality the entropy underlying it does not). It's not possible to directly convert 243 bits to a mnemonic, so a hash is used in that case.

https://github.com/iancoleman/bip39/blob/90f7a5ec9309c755dd06a534190067fa6f1f97fe/src/js/index.js#L1620-L1642
