### ISSUE TITLE
new entropy modifications not working ?

### ISSUE THREAD

**Issue by jpph** [iancoleman/bip39#457]
I have tested 0.5.0 and 0.4.3, with same dice roll, they produce different raw binary entropy but same 24 words bip39 mnemonic.
For example :
dice roll : 12345612341234561234123456123412345612341234561234  (123456 1234 five times)
new version binary : 
01101101000 11011001101 10100011011 00110110100 01101100110 11010001101 10011011010 00110110
old version binary :  
01001000111 01100010011 10000010011 10111110011 11101110011 10001010111 00100001110 11011110011 11111011011 11010001000 00101100010 10010110

But 24 words bip39 is the same for both : reduce prefer put marriage reform genuine carbon diagram lounge night grace put brown loud cover chuckle plug open very oval cupboard scene album receive

**Comment by iancoleman** [comment]
Any selection of entropy into a fixed number of words will hash the entropy string as entered (ie not hash the binary conversion). This happens on [L1702 of index.js](https://github.com/iancoleman/bip39/blob/4e59e7d6fcafa09d2f35542349ee0be2eaebc1ed/src/js/index.js#L1702). The hash result is then used as the binary (and truncated if needed).

D6 generates log<sub>2</sub>(6) ~2.58 bits of entropy per roll. It's most sensible to simply take the exact entropy as entered (which may overall represent some non-integer amount of entropy) rather than the conversion into binary entropy.

**Comment by jpph** [comment]
Ok, thank you for the clarification. Closing....
