### ISSUE TITLE
Suggestion: Bitcoin Donations?

### ISSUE THREAD

**Issue by ElvisRe** [iancoleman/bip39#51]
Useful code, thanks! How about adding your bitcoin donations address?

**Comment by iancoleman** [comment]
Thanks for this, it's a great idea.

I'm proposing to add an address or donation link to a worthy cause in the readme of the project (my preferred not-for-profit is EFF).

* this tool is the result of many contributors, most of which don't appear in the list of github contributors. Putting an address for just one person feels against the spirit of this project.
* place the link in the readme for the project rather than the tool itself keeps the tool focused on the task at hand. It's already quite complex and wordy.
* I'd prefer to use a bitcoin address rather than payment processor. Unfortunately EFF uses a payment processor to accept bitcoin donations, which adds complexity to the donor experience. Anyone with a suggested organization that uses direct donation addresses, please post the details here for consideration of being added to the readme.

**Comment by ElvisRe** [comment]
Yeah, you're welcome!

Good points, I didn't realize how many people had contributed.

I agree that a bitcoin donation address is the simplest approach.  Here are some organization, causes or non-profits I'd suggest:

[Wikimedia](https://wikimediafoundation.org/wiki/Ways_to_Give#bitcoin)
[Bitcoin Foundation](http://bitcoinfoundation.org/donate/)
[WayBackMachine - archive.org](https://archive.org/donate/bitcoin.php)

Others ideas: [Bitcoin.it's List of Donation-accepting organizations and projects](https://en.bitcoin.it/wiki/Donation-accepting_organizations_and_projects)

**Comment by iancoleman** [comment]
This is now in the readme

[1e6a9f4 - Donations section in readme.md](https://github.com/iancoleman/bip39/commit/1e6a9f416244cf00fa41c1237973de3174fa656f)

Great suggestion.

**Comment by ElvisRe** [comment]
You're welcome, and thank you!  Looks like the link to Free Software
Foundation <https://my.fsf.org/civicrm/contribute/transact> is not
working.  It must rely on session cookies or something.  Perhaps this link
instead: https://www.fsf.org/about/ways-to-donate/  ?

**Comment by iancoleman** [comment]
Thanks for this.

See https://github.com/iancoleman/bip39/commit/982e4e75c74b2f7d86d95190928cc36ab9e6847e - FSF donation link updated to working link
