### ISSUE TITLE
Is it possible to use for Ethereum?

### ISSUE THREAD

**Issue by Nogreedy** [iancoleman/bip39#54]
Is it possible to use for Ethereum?
e.g. with Metamask (12 words seed).
Thanks in advance for your answer.

**Comment by iancoleman** [comment]
This should be possible. I'll investigate the possibility and if all is good will implement it.

Notes:

* see [networks](https://github.com/iancoleman/bip39/blob/53aaab270d7031a05ffe66f424529ea84534fb40/src/js/index.js#L1034) variable
* see [bitcoinjs-extensions.js](https://github.com/iancoleman/bip39/blob/53aaab270d7031a05ffe66f424529ea84534fb40/src/js/bitcoinjs-extensions.js)
* ethereum is not listed in [bitcoinjs-lib/networks.js](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/networks.js)

**Comment by iancoleman** [comment]
My research so far:

https://walletgenerator.net/ does not support ethereum which is a bad sign since they support many blockchains (see [these reddit comments](https://www.reddit.com/r/ethereum/comments/3gbhui/how_do_i_generate_an_eth_private_key/) for more info, looks like over a year that the opportunity to add ethereum has gone unattended).

ethereumjs-util shows [pubToAddress uses sha3 hashing](https://github.com/ethereumjs/ethereumjs-util/blob/499732851ba03109bf8bf89311b00038a6c89580/index.js#L319) which is again not looking promising.

If anyone with more knowledge of ethereum can chime in here that would be really handy. For now I'll leave this issue open pending further info.

**Comment by blogin** [comment]
@Nogreedy Functionality of converting BIP39 mnemonic words to ether addresses is available here: https://www.myetherwallet.com/#view-wallet-info. To generate select "Mnemonic Phrase", enter mnemonic words and click "Unlock" button. 

Myetherwallet is rather a tool for end-users, than for developers, because it does not expose extended BIP32 private and public keys, so it may be necessary to use both tools, depending on what is your goal.

**Comment by iancoleman** [comment]
https://github.com/ethereumjs/ethereumjs-util has all the required functionality. It adds about 500 kB of code, but I think it's worth it to be able to include the second-biggest cryptocurrency in the tool.

I've implemented this and should hopefully have it released in a few days once I get time to look at some obscure breakage of the ethereum tests.

Thanks for the pointers @blogin. myetherewallet is very nice!

**Comment by Nogreedy** [comment]
@iancoleman Thanks so much

**Comment by iancoleman** [comment]
See

https://github.com/iancoleman/bip39/commit/505a31593ec3ead7200c9e181641ba7e3a7b5243 - Ethereum Util library
https://github.com/iancoleman/bip39/commit/0edac945e597099d1cabfa684e3c172b3d70cf6c - Ethereum address table is populated
https://github.com/iancoleman/bip39/commit/24137d96070eb6cb47ef8239738ec6a135f0b675 - Ethereum tests
https://github.com/iancoleman/bip39/commit/8b095871e8ab14ec236ddb181ffdfe36e6636058 - Ethereum compiled into standalone

Steps to use:

* Enter mnemonic
* Select 'Ethereum' from the 'Coin' selection
* See the address table is populated
* See that using same mnemonic or private key in [MyEtherWallet](https://www.myetherwallet.com/#view-wallet-info) gives matching results

I'm not too familiar with ethereum and have based the tests for correctness on those generated by https://www.myetherwallet.com/#view-wallet-info

Anyone with better understanding of ethereum would be most welcome to provide feedback.

**Comment by akumthek** [comment]
Wow nice effort
