### ISSUE TITLE
Getting same word in mnumonic phrase 3-24 word length (with extremely strong rating)

### ISSUE THREAD

**Issue by SilentCicero** [iancoleman/bip39#76]
When entering random keyboard entropy into the Mnumonic word generator (just key smashing) even with an extremely strong rating I've gotten the same word twice in a 24 word phrase.

How bad/insecure is it when a word in your mnumonic gets repeated twice? Usually I just generate a seed until I get a list of words that dont repeat - then I have a strong passphrase on that. I usually use a combination of virtual keyboard (click smashing), key smashing, different angles of key smashing, then system entropy with /dev/urandom (this is what I'm recommending for people).

Thoughts?

Should there be a basic check for this kind of thing? Is there something going wrong with the generator? Should I be concerned even if I recommend to people to use a complex passphrase as well?

I'll be recommending this tool, so I want every loose end covered/thought about.

Best, Nick

**Comment by iancoleman** [comment]
> How bad/insecure is it when a word in your mnumonic gets repeated twice?

Not bad/insecure at all. Actually if it were impossible to have repeated words the strength would be less.

> Usually I just generate a seed until I get a list of words that dont repeat

This is not necessary to ensure the strength of the mnemonic. An attacker is actually more easily able to break this since if they see a mnemonic with two words (which should be totally valid under standard bip39 rules) they know they wouldn't need to check it under your special 'no repeat words rule', so the total work for the attacker would be (very slightly) reduced.

> I usually use a combination of [sources of randomness]...

This is fine. As an aside, I personally don't consider keyboard smashing to be good enough for random numbers. Used in combination like you say is no problem (overkill if anything!)

Lot more discussion about the entropy feature in https://github.com/iancoleman/bip39/issues/21

I'm excited about the documents you are producing and would be keen to see them once they're ready. Please do let me know once you get to releasing them.
