### ISSUE TITLE
checksum not standard from - say bitcore

### ISSUE THREAD

**Issue by kensilverman** [iancoleman/bip39#85]
reproduce:

1)  make a hex entropy of 256bits  (64 chars) and note the 24 words
2)  delete the final digit of entropy  and add a different digit and note the 24 words

In case 1 and 2 the words are COMPLETELY different.  but if you look at the bip 39 spec.  and you look at a reference implementation of, say, Bitcore,  you'll see very clearly that the checksum hash, first 8 bits are added to the *END* of the entropy.  That means the first 22 words (those in the 1st 253 bits) should stay exactly the same.    Why is your implementation different than this???  Or what am I missing.  Ive gone so far as to examine the code of Bitcore and I can clearly see that the sha 1st 8 bits are added to the END of the entropy and that the entropy itself is used in order of the string from beginning to end to create 11 bit words - therefore all the words should NOT change just because you swap out the last digit (bits 252-255) of the entropy.   Yes, the hash changes - but the hash is used only to add the first 8 bits of it to the **end** of the entropy.   The 1st 252 bits and therefore 1st 22 words (22 * 11 is less than 252 bits)  should not change.   

Solved:  I believe you simply take a different hash of the raw entropy to create a new entropy before you continue with checksum and word creation.

**Comment by kensilverman** [comment]
In an ideal world,  I would be able to create words just from looking at the bip39 spec. and coding any implementation of it.  Then I would be able to copy them into any checker, and it would not say "invalid mnemonic".  So the logical assumption, is that I am missing something.   Perhaps shedding light on your checksum and entropy implementation will help.  Thanks.

**Comment by iancoleman** [comment]
> That means the first 22 words (those in the 1st 253 bits) should stay exactly the same

Select 'Use raw entropy' for the Mnemonic Length dropdown. This will give the behaviour you're expecting.

If you select '24 Words' from the dropdown the entropy will be hashed before being converted to a mnemonic, giving the 'unexpected' behaviour you've described. This option is given so that 'too much' or 'too little' entropy will always result in 24 words (or 12 words or 15 etc...). A lot of discussion about the entropy feature (including the reason for the 'unexpected' behaviour) is in https://github.com/iancoleman/bip39/issues/21 and https://github.com/iancoleman/bip39/issues/33.

> if the raw entropy was not too random, then they can brute force
>
> could be some sort of bip in an attempt to protect not truly random generated entropies
> etc

Don't use entropy that's 'not too random' or 'not truly random'; use proper randomness for entropy. Don't try to reinvent 'some sort of bip'; follow standard practices. Read the warning on the page about entropy and randomness. BIP39 and BIP32 allow as much (or as little) entropy required for bitcoin keys.

> The bip might describe a protective measure of randomizing, reprodubile only with yet another password

Use the BIP39 Passphrase field. Extra passphrase fields are unnecessary if this field is used correctly.
