### ISSUE TITLE
Ripple secret Key

### ISSUE THREAD

**Issue by asifssarker** [iancoleman/bip39#90]
From seed Mnemonic Code Converter generates the private key but for Ripple we need the secret key. So how can we get it?

**Comment by iancoleman** [comment]
See https://github.com/iancoleman/bip39/pull/70#issuecomment-306123619

> In http://ripplepaperwallet.com or gatehub, they use a "Secret" and not a private key to recover accounts. You can easily derive a private key from a secret using deriveKeypair but not the contrary.
>
> So, it would be possible to represent the private key in WIF format but no platform uses it yet, so I sticked with Hex which is the format supported for signing transaction by the ripple-lib

I don't know much about ripple so I would suggest asking on a ripple forum. If you do and receive an answer, please post a link to the thread in this issue so I can learn more.

**Comment by alkley** [comment]
Ledger made a tool for this: https://github.com/LedgerHQ/ripple-recovery-tool

I also once came across a browser based client that took either the secret key or an address/private key combination. I cannot find it anymore but it is out there.

**Comment by asifssarker** [comment]
Great! you guys are awesome, thanks. Even though it is not generating the secret but at least we can do something with it. Could you tell me which derivation path need to select , BIP32 or BIP44 when recovering from the seed using the bip39? As it changes everything the address and the private key, so confusing.

**Comment by iancoleman** [comment]
I suggest these questions be asked to ripple support people; I'm not familiar with ripple or ripple wallets so my advice is not especially useful in this case.

My best guess (which is only based on a small amount of research so should be considered unreliable) is you can use whatever derivation scheme you want in this tool. I don't know any end-user ripple wallets that implement BIP44 or BIP39 or BIP32 directly. So my suggestion is this tool should be used only for generating keys (however you want), which can then be used separately in ripple wallets.

The ledger tool seems good for using private keys rather than seeds (but that's the only feature I tested so don't know if it's good for anything else).

**Comment by asifssarker** [comment]
I wasn't interesting in any particular product or looking for any support team but just to learn the technology behind it. I found your BIP39 is interesting so wanna to know bit more of its utility. Thanks anyway:)
